# Generated by Django 3.1.3 on 2023-06-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinamo_app_gerente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nomre_producto',
            new_name='nombre_producto',
        ),
    ]
