# Generated by Django 3.1.3 on 2023-05-27 17:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('precio', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('año', models.CharField(max_length=10)),
                ('caracteristicas', models.CharField(max_length=300)),
                ('kilometraje', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Auto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('nomre_producto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Sucursal',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.rol')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.sucursal')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(default=0)),
                ('nombre_vendedor', models.CharField(max_length=100)),
                ('fecha_venta', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=200)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('cedula_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.usuario')),
                ('id_auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.auto')),
            ],
            options={
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('cantidadMinima', models.IntegerField(default=0)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.proveedor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.sucursal')),
            ],
            options={
                'db_table': 'Repuesto',
            },
        ),
        migrations.CreateModel(
            name='RegistroTaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_auto', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=200)),
                ('fecha_ingreso', models.CharField(max_length=100)),
                ('fecha_entregado', models.CharField(max_length=100)),
                ('costo_reparacion', models.IntegerField(default=0)),
                ('mecanico_encargado', models.CharField(max_length=100)),
                ('cedula_mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.usuario')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.sucursal')),
            ],
            options={
                'db_table': 'RegistroTaller',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=100)),
                ('cantidad_pago', models.IntegerField(default=0)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('meotodo_pago', models.CharField(max_length=100)),
                ('cedula_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.usuario')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.venta')),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.IntegerField(default=0)),
                ('intereses', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fecha_inicio_cuotas', models.CharField(max_length=50)),
                ('fecha_fin_cuotas', models.CharField(max_length=50)),
                ('estado_pago', models.CharField(max_length=50)),
                ('monto_restante', models.IntegerField(default=0)),
                ('cedula_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.usuario')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.venta')),
            ],
            options={
                'db_table': 'Credito',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=200)),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('cedula_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cedula_cliente', to='dinamo_app_gerente.usuario')),
                ('cedula_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cedula_empleado', to='dinamo_app_gerente.usuario')),
            ],
            options={
                'db_table': 'Cita',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.proveedor'),
        ),
        migrations.AddField(
            model_name='auto',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.sucursal'),
        ),
    ]
