# Generated by Django 3.1.3 on 2023-06-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamo_app_gerente', '0002_auto_20230608_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.CharField(max_length=200)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.rol')),
            ],
            options={
                'db_table': 'Reporte',
            },
        ),
    ]
