# Generated by Django 3.1.3 on 2023-06-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamo_app_gerente', '0003_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(default='Reporte', max_length=200),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='archivo_pdf',
            field=models.FileField(upload_to='reportes'),
        ),
    ]
