# Generated by Django 3.1.3 on 2023-07-01 15:30

import dinamo_app_gerente.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamo_app_gerente', '0005_auto_20230628_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='archivo_pdf',
            field=models.FileField(upload_to='reportes', validators=[dinamo_app_gerente.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='Correo Eléctronico'),
        ),
    ]
