# Generated by Django 3.1.3 on 2023-07-04 22:08

import dinamo_app_gerente.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamo_app_gerente', '0006_auto_20230701_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[dinamo_app_gerente.validators.validate_numeric], verbose_name='Cédula'),
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.usuario')),
            ],
            options={
                'db_table': 'Quejas',
            },
        ),
    ]
