# Generated by Django 3.1.3 on 2023-07-04 23:22

import cloudinary.models
import dinamo_app_gerente.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamo_app_gerente', '0008_auto_20230704_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='año',
            field=models.CharField(max_length=10, validators=[dinamo_app_gerente.validators.validate_numeric]),
        ),
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(max_length=50, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='auto',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[dinamo_app_gerente.validators.validate_file_extension_imgs]),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.CharField(max_length=10, validators=[dinamo_app_gerente.validators.validate_fecha_format]),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre_cliente',
            field=models.CharField(max_length=100, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre_empleado',
            field=models.CharField(max_length=100, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='credito',
            name='estado_pago',
            field=models.CharField(max_length=50, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_fin_cuotas',
            field=models.CharField(max_length=10, validators=[dinamo_app_gerente.validators.validate_fecha_format]),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_inicio_cuotas',
            field=models.CharField(max_length=10, validators=[dinamo_app_gerente.validators.validate_fecha_format]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='meotodo_pago',
            field=models.CharField(max_length=100, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='nombre_cliente',
            field=models.CharField(max_length=200, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(max_length=100, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=50, validators=[dinamo_app_gerente.validators.validate_numeric]),
        ),
        migrations.AlterField(
            model_name='registrotaller',
            name='estado',
            field=models.CharField(max_length=50, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='registrotaller',
            name='fecha_entregado',
            field=models.CharField(max_length=100, validators=[dinamo_app_gerente.validators.validate_fecha_format]),
        ),
        migrations.AlterField(
            model_name='registrotaller',
            name='fecha_ingreso',
            field=models.CharField(max_length=100, validators=[dinamo_app_gerente.validators.validate_fecha_format]),
        ),
        migrations.AlterField(
            model_name='registrotaller',
            name='mecanico_encargado',
            field=models.CharField(max_length=100, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='correo',
            field=models.CharField(max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(max_length=50, validators=[dinamo_app_gerente.validators.validate_numeric]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=200, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=200, validators=[dinamo_app_gerente.validators.validate_numeric], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.CharField(max_length=100, validators=[dinamo_app_gerente.validators.validate_fecha_format]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(max_length=50, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombre_vendedor',
            field=models.CharField(max_length=100, validators=[dinamo_app_gerente.validators.validate_str]),
        ),
    ]
