# Generated by Django 3.1.3 on 2023-07-05 18:33

import dinamo_app_gerente.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamo_app_gerente', '0009_auto_20230704_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveBigIntegerField(default=0)),
                ('placa', models.CharField(max_length=50)),
                ('fecha_ingreso', models.CharField(max_length=10, validators=[dinamo_app_gerente.validators.validate_fecha_format])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.usuario')),
            ],
            options={
                'db_table': 'AutoTaller',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10, validators=[dinamo_app_gerente.validators.validate_fecha_format])),
                ('descripcion', models.TextField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.autotaller')),
            ],
            options={
                'db_table': 'OrdenTrabajo',
            },
        ),
    ]
