# Generated by Django 3.1.3 on 2023-07-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinamo_app_gerente', '0012_auto_20230705_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cotizacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dinamo_app_gerente.cotizacion'),
        ),
    ]
